# Finding the Neareast Neighbors

## -NearestNeighbors parameter
### n_neighbors : int, default=5 ==> Number of neighbors to use by default for kneighbors queries
### radius : float, default=1.0 ==> Range of parameter space to use by default for radius_neighbors queries
### algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto' ==> Algorithm used to compute the nearest neighbors
### leaf_size : int, default=30 ==> This can affect the speed of the construction and query, as well as the memory required to store the tree
### n_jobs : int, default=None ==> The number fo parallel jobs to run for neighbors search

In [1]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

X=np.array([[-1,-1],[-2,1],[-3,-2],[1,1],[2,1],[3,2]])
nbrs=NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)

In [2]:
distances, indices=nbrs.kneighbors(X)

In [3]:
indices

array([[0, 1],
       [1, 0],
       [2, 0],
       [3, 4],
       [4, 3],
       [5, 4]])

In [4]:
distances

array([[0.        , 2.23606798],
       [0.        , 2.23606798],
       [0.        , 2.23606798],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356]])

In [5]:
samples=[[0,0,2],[1,0,0],[0,0,1]]

In [6]:
neigh=NearestNeighbors(n_neighbors=2, radius=0.4)
neigh.fit(samples)

NearestNeighbors(n_neighbors=2, radius=0.4)

In [8]:
neigh.kneighbors([[0,0,1.3]], 2, return_distance=False)

array([[2, 0]])

In [9]:
nbrs=neigh.radius_neighbors(
    [[0,0,1.3]], 0.4, return_distance=False
)
np.asarray(nbrs[0][0])

array(2)

In [10]:
samples=[[0. , 0., 0.],[0., .5, 0.], [1., 1., .5]]

neigh=NearestNeighbors(n_neighbors=1)
neigh.fit(samples)
print(neigh.kneighbors([[1., 1., 1.]]))

(array([[0.5]]), array([[2]]))


거리가 0.5이고 샘플의 세번째 요소이다

In [11]:
X=[[0. , 1., 0.], [1., 0., 1.]]
neigh.kneighbors(X, return_distance=False)

array([[1],
       [2]])